//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int ID_Client { get; set; }
        public string Title { get; set; }
        public Nullable<System.DateTime> Registration_Date { get; set; }
        public Nullable<int> ID_Employee { get; set; }
        public string Address { get; set; }
        public string Post_Address { get; set; }
        public string UNN_UNP { get; set; }
        public string Kind_Activity { get; set; }
        public Nullable<int> Rating { get; set; }
    }
}
