//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ID_Content { get; set; }
        public string Text { get; set; }
        public int ID_Content_Type { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<int> IsRead { get; set; }
        public Nullable<int> Important { get; set; }
    }
}
