//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact_Name
    {
        public int ID_Contact_Name { get; set; }
        public string FIO { get; set; }
        public string Post { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.TimeSpan> Dinner_Time { get; set; }
        public int ID_Clients { get; set; }
        public int Type { get; set; }
    }
}
